import { Body } from "@/styles/layout.styles"

export const metadata = {
  title: 'Link Facul',
  description: 'Generated by Next.js',
}

export const revalidate = 0;
export const dynamic = "force-dynamic";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Body>{children}</Body>
    </html>
  )
}
